FAKE_CASES = [
    {"case_id": "CASE_001", "sender": "PERSON_001", "receiver": "PERSON_045", "amount": 45000, "narrative": "High value transfer to new recipient, unusual location, flagged as fraud"},
    {"case_id": "CASE_002", "sender": "PERSON_002", "receiver": "PERSON_046", "amount": 5000, "narrative": "Small routine transfer to known recipient, normal pattern"},
    {"case_id": "CASE_003", "sender": "PERSON_003", "receiver": "PERSON_047", "amount": 98000, "narrative": "Very large transfer at unusual hour, recipient linked to watchlist"},
    {"case_id": "CASE_004", "sender": "PERSON_004", "receiver": "PERSON_048", "amount": 12000, "narrative": "Multiple rapid transfers to same new recipient within minutes, suspicious"},
    {"case_id": "CASE_005", "sender": "PERSON_005", "receiver": "PERSON_049", "amount": 3000, "narrative": "Small transfer, matches usual monthly spending pattern, not flagged"},
    {"case_id": "CASE_006", "sender": "PERSON_006", "receiver": "PERSON_050", "amount": 67000, "narrative": "High value transfer from new device and new location simultaneously"},
    {"case_id": "CASE_007", "sender": "PERSON_007", "receiver": "PERSON_051", "amount": 15000, "narrative": "Transfer to recipient with multiple prior fraud reports"},
    {"case_id": "CASE_008", "sender": "PERSON_008", "receiver": "PERSON_052", "amount": 2000, "narrative": "Routine grocery-level transaction, no anomaly"},
    {"case_id": "CASE_009", "sender": "PERSON_009", "receiver": "PERSON_053", "amount": 55000, "narrative": "Large transfer immediately after login from unrecognized device"},
    {"case_id": "CASE_010", "sender": "PERSON_010", "receiver": "PERSON_054", "amount": 8000, "narrative": "Transfer amount slightly above usual average, minor anomaly"},
    {"case_id": "CASE_011", "sender": "PERSON_011", "receiver": "PERSON_055", "amount": 120000, "narrative": "Extremely high value transfer, first-time recipient, foreign account"},
    {"case_id": "CASE_012", "sender": "PERSON_012", "receiver": "PERSON_056", "amount": 4000, "narrative": "Normal recurring subscription payment, no flags"},
    {"case_id": "CASE_013", "sender": "PERSON_013", "receiver": "PERSON_057", "amount": 30000, "narrative": "Transfer during unusual night hours, recipient recently added"},
    {"case_id": "CASE_014", "sender": "PERSON_014", "receiver": "PERSON_058", "amount": 76000, "narrative": "High value transfer, new recipient, location mismatch with usual pattern"},
    {"case_id": "CASE_015", "sender": "PERSON_015", "receiver": "PERSON_059", "amount": 6000, "narrative": "Small transfer consistent with prior spending, no anomaly detected"},
    {"case_id": "CASE_016", "sender": "PERSON_016", "receiver": "PERSON_060", "amount": 42000, "narrative": "Transfer to recipient linked to sanctions watchlist, high risk"},
    {"case_id": "CASE_017", "sender": "PERSON_017", "receiver": "PERSON_061", "amount": 9000, "narrative": "Slightly higher than average transfer, minor deviation, low risk"},
    {"case_id": "CASE_018", "sender": "PERSON_018", "receiver": "PERSON_062", "amount": 89000, "narrative": "Very large transfer, account recently reactivated, high anomaly score"},
    {"case_id": "CASE_019", "sender": "PERSON_019", "receiver": "PERSON_063", "amount": 3500, "narrative": "Routine bill payment, matches usual pattern"},
    {"case_id": "CASE_020", "sender": "PERSON_020", "receiver": "PERSON_064", "amount": 51000, "narrative": "High value transfer shortly after password reset, suspicious timing"},
    {"case_id": "CASE_021", "sender": "PERSON_021", "receiver": "PERSON_065", "amount": 7000, "narrative": "Normal transaction, recipient known for over a year"},
    {"case_id": "CASE_022", "sender": "PERSON_022", "receiver": "PERSON_066", "amount": 63000, "narrative": "Transfer to new recipient in different country, high value, flagged"},
    {"case_id": "CASE_023", "sender": "PERSON_023", "receiver": "PERSON_067", "amount": 4500, "narrative": "Small transaction within normal monthly budget"},
    {"case_id": "CASE_024", "sender": "PERSON_024", "receiver": "PERSON_068", "amount": 99000, "narrative": "Extremely large transfer, multiple risk factors, new device and location"},
    {"case_id": "CASE_025", "sender": "PERSON_025", "receiver": "PERSON_069", "amount": 2500, "narrative": "Routine small transfer, no fraud indicators"}
]